"""
Helper to map Bible book abbreviations/titles in Coptic Scriptorium to standard English and Arabic names.
"""

BOOK_MAP = {
    # New Testament
    '40_Matthew': ('Matthew', 'متى', 'nt.matt'),
    '41_Mark': ('Mark', 'مرقس', 'nt.mark'),
    '42_Luke': ('Luke', 'لوقا', 'nt.luke'),
    '43_John': ('John', 'يوحنا', 'nt.john'),
    '44_Acts': ('Acts', 'أعمال الرسل', 'nt.acts'),
    '45_Romans': ('Romans', 'رومية', 'nt.rom'),
    '46_1Corinthians': ('1 Corinthians', '1 كورنثوس', 'nt.1cor'),
    '47_2Corinthians': ('2 Corinthians', '2 كورنثوس', 'nt.2cor'),
    '48_Galatians': ('Galatians', 'غلاطية', 'nt.gal'),
    '49_Ephesians': ('Ephesians', 'أفسس', 'nt.eph'),
    '50_Philippians': ('Philippians', 'فيلبي', 'nt.phil'),
    '51_Colossians': ('Colossians', 'كولوسي', 'nt.col'),
    '52_1Thessalonians': ('1 Thessalonians', '1 تسالونيكي', 'nt.1thess'),
    '53_2Thessalonians': ('2 Thessalonians', '2 تسالونيكي', 'nt.2thess'),
    '54_1Timothy': ('1 Timothy', '1 تيموثاوس', 'nt.1tim'),
    '55_2Timothy': ('2 Timothy', '2 تيموثاوس', 'nt.2tim'),
    '56_Titus': ('Titus', 'تيطس', 'nt.titus'),
    '57_Philemon': ('Philemon', 'فليمون', 'nt.phlm'),
    '58_Hebrews': ('Hebrews', 'العبرانيين', 'nt.heb'),
    '59_James': ('James', 'يعقوب', 'nt.jas'),
    '60_1Peter': ('1 Peter', '1 بطرس', 'nt.1pet'),
    '61_2Peter': ('2 Peter', '2 بطرس', 'nt.2pet'),
    '62_1John': ('1 John', '1 يوحنا', 'nt.1john'),
    '63_2John': ('2 John', '2 يوحنا', 'nt.2john'),
    '64_3John': ('3 John', '3 يوحنا', 'nt.3john'),
    '65_Jude': ('Jude', 'يهوذا', 'nt.jude'),
    '66_Revelation': ('Revelation', 'رؤيا يوحنا', 'nt.rev'),
    
    # Old Testament
    '01_Genesis': ('Genesis', 'التكوين', 'ot.gen'),
    '02_Exodus': ('Exodus', 'الخروج', 'ot.exod'),
    '03_Leviticus': ('Leviticus', 'اللاويين', 'ot.lev'),
    '04_Numbers': ('Numbers', 'العدد', 'ot.num'),
    '05_Deuteronomy': ('Deuteronomy', 'التثنية', 'ot.deut'),
    '06_Joshua': ('Joshua', 'يشوع', 'ot.josh'),
    '07_Judges': ('Judges', 'القضاة', 'ot.judg'),
    '08_Ruth': ('Ruth', 'راعوث', 'ot.ruth'),
    '09_1Samuel': ('1 Samuel', '1 صموئيل', 'ot.1sam'),
    '10_2Samuel': ('2 Samuel', '2 صموئيل', 'ot.2sam'),
    '11_1Kings': ('1 Kings', '1 ملوك', 'ot.1kgs'),
    '12_2Kings': ('2 Kings', '2 ملوك', 'ot.2kgs'),
    '19_Psalms': ('Psalms', 'المزامير', 'ot.pss'),
    '20_Proverbs': ('Proverbs', 'الأمثال', 'ot.prov'),
    '21_Ecclesiastes': ('Ecclesiastes', 'الجامعة', 'ot.eccl'),
    '22_SongOfSolomon': ('Song of Solomon', 'نشيد الأنشاد', 'ot.song'),
    '23_Isaiah': ('Isaiah', 'إشعياء', 'ot.isa'),
    '24_Jeremiah': ('Jeremiah', 'إرميا', 'ot.jer'),
    '27_Daniel': ('Daniel', 'دانيال', 'ot.dan'),
    '28_Hosea': ('Hosea', 'هوشع', 'ot.hos'),
    '29_Joel': ('Joel', 'يوئيل', 'ot.joel'),
    '30_Amos': ('Amos', 'عاموس', 'ot.amos'),
    '31_Obadiah': ('Obadiah', 'عوبديا', 'ot.obad'),
    '32_Jonah': ('Jonah', 'يونان', 'ot.jonah'),
    '33_Micah': ('Micah', 'ميخا', 'ot.mic'),
    '34_Nahum': ('Nahum', 'ناحوم', 'ot.nah'),
    '35_Habakkuk': ('Habakkuk', 'حبقوق', 'ot.hab'),
    '36_Zephaniah': ('Zephaniah', 'صفنيا', 'ot.zeph'),
    '37_Haggai': ('Haggai', 'حجي', 'ot.hag'),
    '38_Zechariah': ('Zechariah', 'زكريا', 'ot.zech'),
    '39_Malachi': ('Malachi', 'ملاخي', 'ot.mal')
}
