import json
import os

concordance_entries = [
  {
    "id": "cit_noute_john_1_1",
    "lemma": "ⲛⲟⲩⲧⲉ",
    "matched_form": "ⲡⲛⲟⲩⲧⲉ",
    "source_name": "Gospel of John (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲓⲱϩⲁⲛⲛⲏⲥ)",
    "reference": "John 1:1",
    "urn": "urn:cts:copticLit:nt.john.sahidica:1.1",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ϩⲛ ⲧⲉϩⲟⲩⲉⲓⲧⲉ ⲛⲉϥϣⲟⲟⲡ ⲛϭⲓ ⲡϣⲁϫⲉ ⲁⲩⲱ ⲡϣⲁϫⲉ ⲛⲉϥϣⲟⲟⲡ ϩⲁ ⲡⲛⲟⲩⲧⲉ ⲁⲩⲱ ⲛⲉⲩⲛⲟⲩⲧⲉ ⲡⲉ ⲡϣⲁϫⲉ.",
    "english_translation": "In the beginning was the Word, and the Word was with God, and the Word was God.",
    "arabic_translation": "فِي الْبَدْءِ كَانَ الْكَلِمَةُ، وَالْكَلِمَةُ كَانَ عِنْدَ اللهِ، وَكَانَ الْكَلِمَةُ اللهَ."
  },
  {
    "id": "cit_noute_john_3_16",
    "lemma": "ⲛⲟⲩⲧⲉ",
    "matched_form": "ⲡⲛⲟⲩⲧⲉ",
    "source_name": "Gospel of John (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲓⲱϩⲁⲛⲛⲏⲥ)",
    "reference": "John 3:16",
    "urn": "urn:cts:copticLit:nt.john.sahidica:3.16",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲧⲁⲓ ⲅⲁⲣ ⲧⲉ ⲧϩⲉ ⲉⲛⲧⲁ ⲡⲛⲟⲩⲧⲉ ⲙⲉⲣⲉ ⲡⲕⲟⲥⲙⲟⲥ ϩⲱⲥⲧⲉ ⲡⲉϥϣⲏⲣⲉ ⲛⲟⲩⲱⲧ ⲁϥⲧⲁⲁϥ ϫⲉⲕⲁⲥ ⲟⲩⲟⲛ ⲛⲓⲙ ⲉⲧⲡⲓⲥⲧⲉⲩⲉ ⲉⲣⲟϥ ⲛⲛⲉϥϩⲉ ⲉⲃⲟⲗ ⲁⲗⲗⲁ ⲉϥⲉϫⲓ ⲛⲟⲩⲱⲛϩ ϣⲁ ⲉⲛⲉϩ.",
    "english_translation": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    "arabic_translation": "لأَنَّهُ هكَذَا أَحَبَّ اللهُ الْعَالَمَ حَتَّى بَذَلَ ابْنَهُ الْوَحِيدَ، لِكَيْ لاَ يَهْلِكَ كُلُّ مَنْ يُؤْمِنُ بِهِ، بَلْ تَكُونُ لَهُ الْحَيَاةُ الأَبَدِيَّةُ."
  },
  {
    "id": "cit_noute_gen_1_1",
    "lemma": "ⲛⲟⲩⲧⲉ",
    "matched_form": "ⲡⲛⲟⲩⲧⲉ",
    "source_name": "Genesis (ⲅⲉⲛⲉⲥⲓⲥ - CoptOT)",
    "reference": "Genesis 1:1",
    "urn": "urn:cts:copticLit:ot.gen.coptot:1.1",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ϩⲛ ⲧⲉϩⲟⲩⲉⲓⲧⲉ ⲁ ⲡⲛⲟⲩⲧⲉ ⲧⲁⲙⲓⲟ ⲛⲧⲡⲉ ⲙⲛ ⲡⲕⲁϩ.",
    "english_translation": "In the beginning God created the heaven and the earth.",
    "arabic_translation": "فِي الْبَدْءِ خَلَقَ اللهُ السَّمَاوَاتِ وَالأَرْضَ."
  },
  {
    "id": "cit_noute_shenoute_amazed",
    "lemma": "ⲛⲟⲩⲧⲉ",
    "matched_form": "ⲡⲛⲟⲩⲧⲉ",
    "source_name": "St. Shenoute the Archimandrite: I am Amazed (ⲁⲛⲟⲕ ⲅⲁⲣ ϯⲣϣⲡⲏⲣⲉ)",
    "reference": "Shenoute, Canon 6 (MONB.YA:42-47)",
    "urn": "urn:cts:copticLit:shenoute.abraham.monbya:42-47",
    "genre": "monastic",
    "dialect": "Sahidic",
    "coptic_text": "ⲡⲛⲟⲩⲧⲉ ⲅⲁⲣ ⲙⲡⲉϥⲧⲁⲙⲓⲉ ⲡⲣⲱⲙⲉ ⲉⲧⲣⲉϥⲣ ⲡⲟⲛⲏⲣⲟⲥ ⲁⲗⲗⲁ ⲉⲧⲣⲉϥⲥⲙⲟⲩ ⲉⲣⲟϥ ϩⲛ ⲟⲩⲙⲉ.",
    "english_translation": "For God did not create man that he should do evil, but that he should bless Him in truth.",
    "arabic_translation": "لأن الله لم يخلق الإنسان ليفعل الشر، بل ليباركه بالحق."
  },
  {
    "id": "cit_agape_1cor_13_4",
    "lemma": "ⲁⲅⲁⲡⲏ",
    "matched_form": "ⲧⲁⲅⲁⲡⲏ",
    "source_name": "First Epistle to the Corinthians (ⲧⲉⲡⲓⲥⲧⲟⲗⲏ ⲙⲡⲁⲩⲗⲟⲥ ⲡⲣⲟⲥ ⲕⲟⲣⲓⲛⲑⲓⲟⲩⲥ ⲁ)",
    "reference": "1 Corinthians 13:4",
    "urn": "urn:cts:copticLit:nt.1cor.sahidica_ed:13.4",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲧⲁⲅⲁⲡⲏ ϣⲁⲥϩⲁⲣϣ ⲛϩⲏⲧ ⲧⲁⲅⲁⲡⲏ ϣⲁⲥⲣ ⲭⲣⲏⲥⲧⲟⲥ ⲧⲁⲅⲁⲡⲏ ⲙⲉⲥⲕⲱϩ ⲧⲁⲅⲁⲡⲏ ⲙⲉⲥϫⲟⲥⲉ ⲛϩⲏⲧ ⲙⲉⲥϫⲓⲥⲉ ⲙⲙⲟⲥ.",
    "english_translation": "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.",
    "arabic_translation": "الْمَحَبَّةُ تَتَأَنَّى وَتَرْفُقُ. الْمَحَبَّةُ لاَ تَحْسِدُ. الْمَحَبَّةُ لاَ تَتَفَاخَرُ، وَلاَ تَنْتَفِخُ."
  },
  {
    "id": "cit_agape_ap_116",
    "lemma": "ⲁⲅⲁⲡⲏ",
    "matched_form": "ⲧⲁⲅⲁⲡⲏ",
    "source_name": "Apophthegmata Patrum (Sayings of the Desert Fathers)",
    "reference": "Apophthegmata Patrum 116 (MONB.EG)",
    "urn": "urn:cts:copticLit:ap.116.monbeg",
    "genre": "patristic",
    "dialect": "Sahidic",
    "coptic_text": "ⲁϥϫⲟⲟⲥ ⲛϭⲓ ⲟⲩϩⲗⲗⲟ ϫⲉ ⲙⲛ ⲛⲟϭ ⲉ ⲧⲁⲅⲁⲡⲏ ⲙⲛ ⲡⲉⲑⲃⲃⲓⲟ ⲛϩⲏⲧ ϩⲛ ⲛⲉⲧⲉ ⲙⲛⲧⲙⲟⲛⲁⲭⲟⲥ.",
    "english_translation": "An old man said: 'There is nothing greater than love and humility in the monastic life.'",
    "arabic_translation": "قال شيخ: 'ليس شيء أعظم من المحبة والتواضع في سيرة الرهبنة.'"
  },
  {
    "id": "cit_sotp_ps_33_12",
    "lemma": "ⲥⲱⲧⲡ",
    "matched_form": "ⲥⲱⲧⲡ",
    "source_name": "Psalms of David (ⲯⲁⲗⲧⲏⲣⲓⲟⲛ - CoptOT)",
    "reference": "Psalm 33:12 (LXX 32:12)",
    "urn": "urn:cts:copticLit:ot.pss.coptot:32.12",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲛⲁⲓⲁⲧϥ ⲙⲡϩⲉⲑⲛⲟⲥ ⲉⲧⲉ ⲡϫⲟⲉⲓⲥ ⲡⲉ ⲡⲉϥⲛⲟⲩⲧⲉ ⲡⲗⲁⲟⲥ ⲉⲛⲧⲁϥⲥⲟⲧⲡϥ ⲉⲩⲕⲗⲏⲣⲟⲛⲟⲙⲓⲁ ⲛⲁϥ.",
    "english_translation": "Blessed is the nation whose God is the Lord; and the people whom he hath chosen for his own inheritance.",
    "arabic_translation": "طُوبَى لِلأُمَّةِ الَّتِي الرَّبُّ إِلهُهَا، الشَّعْبِ الَّذِي اخْتَارَهُ مِيرَاثاً لِنَفْسِهِ."
  },
  {
    "id": "cit_sotp_ruth_1_22",
    "lemma": "ⲥⲱⲧⲡ",
    "matched_form": "ⲉⲧⲥⲟⲧⲡ",
    "source_name": "Book of Ruth (ⲣⲟⲩⲑ - CoptOT)",
    "reference": "Ruth 1:22",
    "urn": "urn:cts:copticLit:ot.ruth.coptot:1.22",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲁⲩⲱ ⲛⲧⲟⲟⲩ ⲁⲩⲉⲓ ⲉϩⲣⲁⲓ ⲉⲃⲏⲑⲗⲉⲉⲙ ϩⲛ ⲧⲁⲣⲭⲏ ⲙⲡⲱϩⲥ ⲛⲛⲓⲉⲓⲱⲧ ⲉⲧⲥⲟⲧⲡ.",
    "english_translation": "And they came to Bethlehem in the beginning of barley harvest.",
    "arabic_translation": "فَرَجَعَتَا وَدَخَلَتَا بَيْتَ لَحْمٍ فِي ابْتِدَاءِ حَصَادِ الشَّعِيرِ الْمُخْتَارِ."
  },
  {
    "id": "cit_eiwt_matt_6_9",
    "lemma": "ⲉⲓⲱⲧ",
    "matched_form": "ⲡⲉⲛⲉⲓⲱⲧ",
    "source_name": "Gospel of Matthew (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲙⲁⲑⲑⲁⲓⲟⲥ)",
    "reference": "Matthew 6:9 (The Lord's Prayer)",
    "urn": "urn:cts:copticLit:nt.matt.sahidica:6.9",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ϫⲉ ⲡⲉⲛⲉⲓⲱⲧ ⲉⲧϩⲛ ⲙⲡⲏⲩⲉ ⲙⲁⲣⲉ ⲡⲉⲕⲣⲁⲛ ⲟⲩⲟⲡ.",
    "english_translation": "Our Father which art in heaven, Hallowed be thy name.",
    "arabic_translation": "أَبَانَا الَّذِي فِي السَّمَاوَاتِ، لِيَتَقَدَّسِ اسْمُكَ."
  },
  {
    "id": "cit_eiwt_martyrdom_victor",
    "lemma": "ⲉⲓⲱⲧ",
    "matched_form": "ⲡⲉϥⲉⲓⲱⲧ",
    "source_name": "Martyrdom of St. Victor (Budge)",
    "reference": "Martyrdom of St. Victor, fol. 9b",
    "urn": "urn:cts:copticLit:martyrdoms.victor.budge:7-12",
    "genre": "martyrdom",
    "dialect": "Sahidic",
    "coptic_text": "ⲁϥⲁϩⲉⲣⲁⲧϥ ⲛϭⲓ ⲡϩⲁⲅⲓⲟⲥ ⲃⲓⲕⲧⲱⲣ ⲙⲡⲉⲙⲧⲟ ⲉⲃⲟⲗ ⲙⲡⲉϥⲉⲓⲱⲧ ⲣⲱⲙⲁⲛⲟⲥ ⲁⲩⲱ ⲙⲡⲣⲣⲟ ⲇⲓⲟⲕⲗⲏϯⲁⲛⲟⲥ.",
    "english_translation": "Saint Victor stood before his father Romanus and the emperor Diocletian.",
    "arabic_translation": "وقف القديس بقطر أمام أبيه رومانوس والملك دقلديانوس."
  },
  {
    "id": "cit_pneuma_john_4_24",
    "lemma": "ⲡⲛⲉⲩⲙⲁ",
    "matched_form": "ⲟⲩⲡⲛⲉⲩⲙⲁ",
    "source_name": "Gospel of John (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲓⲱϩⲁⲛⲛⲏⲥ)",
    "reference": "John 4:24",
    "urn": "urn:cts:copticLit:nt.john.sahidica:4.24",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲟⲩⲡⲛⲉⲩⲙⲁ ⲡⲉ ⲡⲛⲟⲩⲧⲉ ⲁⲩⲱ ⲛⲉⲧⲟⲩⲱϣⲧ ⲛⲁϥ ϩⲁⲡⲥ ⲉⲧⲣⲉⲩⲟⲩⲱϣⲧ ϩⲛ ⲟⲩⲡⲛⲉⲩⲙⲁ ⲙⲛ ⲟⲩⲙⲉ.",
    "english_translation": "God is a Spirit: and they that worship him must worship him in spirit and in truth.",
    "arabic_translation": "اَللهُ رُوحٌ. وَالَّذِينَ يَسْجُدُونَ لَهُ فَبِالرُّوحِ وَالْحَقِّ يَنْبَغِي أَنْ يَسْجُدُوا."
  },
  {
    "id": "cit_christos_matt_16_16",
    "lemma": "ⲭⲣⲓⲥⲧⲟⲥ",
    "matched_form": "ⲡⲉⲭⲣⲓⲥⲧⲟⲥ",
    "source_name": "Gospel of Matthew (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲙⲁⲑⲑⲁⲓⲟⲥ)",
    "reference": "Matthew 16:16",
    "urn": "urn:cts:copticLit:nt.matt.sahidica:16.16",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲁ ⲥⲓⲙⲱⲛ ⲡⲉⲧⲣⲟⲥ ⲟⲩⲱϣⲃ ⲉϥϫⲱ ⲙⲙⲟⲥ ϫⲉ ⲛⲧⲟⲕ ⲡⲉ ⲡⲉⲭⲣⲓⲥⲧⲟⲥ ⲡϣⲏⲣⲉ ⲙⲡⲛⲟⲩⲧⲉ ⲉⲧⲟⲛϩ.",
    "english_translation": "And Simon Peter answered and said, Thou art the Christ, the Son of the living God.",
    "arabic_translation": "فَأَجَابَ سِمْعَانُ بُطْرُسُ وَقَالَ: 'أَنْتَ هُوَ الْمَسِيحُ ابْنُ اللهِ الْحَيِّ!'"
  },
  {
    "id": "cit_stauros_gal_6_14",
    "lemma": "ⲥⲧⲁⲩⲣⲟⲥ",
    "matched_form": "ⲡⲉⲥⲧⲁⲩⲣⲟⲥ",
    "source_name": "Epistle to the Galatians (ⲧⲉⲡⲓⲥⲧⲟⲗⲏ ⲡⲣⲟⲥ ⲅⲁⲗⲁⲧⲏⲥ)",
    "reference": "Galatians 6:14",
    "urn": "urn:cts:copticLit:nt.gal.sahidica:6.14",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲁⲛⲟⲕ ⲇⲉ ⲛⲛⲉⲥϣⲱⲡⲉ ⲛⲁⲓ ⲉϣⲟⲩϣⲟⲩ ⲙⲙⲟⲓ ⲉⲓ ⲙⲏϯ ϩⲙ ⲡⲉⲥⲧⲁⲩⲣⲟⲥ ⲙⲡⲉⲛϫⲟⲉⲓⲥ ⲓⲏⲥⲟⲩⲥ ⲡⲉⲭⲣⲓⲥⲧⲟⲥ.",
    "english_translation": "But God forbid that I should glory, save in the cross of our Lord Jesus Christ.",
    "arabic_translation": "وَأَمَّا مِنْ جِهَتِي، فَحَاشَا لِي أَنْ أَفْتَخِرَ إِلاَّ بِصَلِيبِ رَبِّنَا يَسُوعَ الْمَسِيحِ."
  },
  {
    "id": "cit_oujai_luke_19_9",
    "lemma": "ⲟⲩϫⲁⲓ",
    "matched_form": "ⲡⲟⲩϫⲁⲓ",
    "source_name": "Gospel of Luke (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲗⲟⲩⲕⲁⲥ)",
    "reference": "Luke 19:9",
    "urn": "urn:cts:copticLit:nt.luke.sahidica:19.9",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲡⲉϫⲁϥ ⲛⲁϥ ⲛϭⲓ ⲓⲏⲥⲟⲩⲥ ϫⲉ ⲙⲡⲟⲟⲩ ⲁ ⲡⲟⲩϫⲁⲓ ϣⲱⲡⲉ ⲙⲡⲉⲓⲏⲓ ⲉⲃⲟⲗ ϫⲉ ⲛⲧⲟϥ ϩⲱⲱϥ ⲟⲩϣⲏⲣⲉ ⲛⲁⲃⲣⲁϩⲁⲙ ⲡⲉ.",
    "english_translation": "And Jesus said unto him, This day is salvation come to this house, forsomuch as he also is a son of Abraham.",
    "arabic_translation": "فَقَالَ لَهُ يَسُوعُ: 'الْيَوْمَ حَصَلَ خَلاَصٌ لِهذَا الْبَيْتِ، إِذْ هُوَ أَيْضاً ابْنُ إِبْرَاهِيمَ.'"
  },
  {
    "id": "cit_shlel_1thess_5_17",
    "lemma": "ϣⲗⲏⲗ",
    "matched_form": "ϣⲗⲏⲗ",
    "source_name": "First Epistle to the Thessalonians (ⲧⲉⲡⲓⲥⲧⲟⲗⲏ ⲡⲣⲟⲥ ⲑⲉⲥⲥⲁⲗⲟⲛⲓⲕⲉⲩⲥ ⲁ)",
    "reference": "1 Thessalonians 5:17",
    "urn": "urn:cts:copticLit:nt.1thess.sahidica:5.17",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ϣⲗⲏⲗ ⲁϫⲛ ⲱϫⲛ ϩⲙ ⲡⲧⲏⲣϥ ϣⲡϩⲙⲟⲧ.",
    "english_translation": "Pray without ceasing. In every thing give thanks.",
    "arabic_translation": "صَلُّوا بِلاَ انْقِطَاعٍ. اشْكُرُوا فِي كُلِّ شَيْءٍ."
  },
  {
    "id": "cit_onh_john_11_25",
    "lemma": "ⲱⲛϩ",
    "matched_form": "ⲡⲱⲛϩ",
    "source_name": "Gospel of John (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲓⲱϩⲁⲛⲛⲏⲥ)",
    "reference": "John 11:25",
    "urn": "urn:cts:copticLit:nt.john.sahidica:11.25",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲡⲉϫⲉ ⲓⲏⲥⲟⲩⲥ ⲛⲁⲥ ϫⲉ ⲁⲛⲟⲕ ⲡⲉ ⲧⲁⲛⲁⲥⲧⲁⲥⲓⲥ ⲁⲩⲱ ⲡⲱⲛϩ ⲡⲉⲧⲡⲓⲥⲧⲉⲩⲉ ⲉⲣⲟⲓ ⲕⲁⲛ ⲉϥϣⲁⲛⲙⲟⲩ ϥⲛⲁⲱⲛϩ.",
    "english_translation": "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.",
    "arabic_translation": "قَالَ لَهَا يَسُوعُ: 'أَنَا هُوَ الْقِيَامَةُ وَالْحَيَاةُ. مَنْ آمَنَ بِي وَلَوْ مَاتَ فَسَيَحْيَا.'"
  },
  {
    "id": "cit_ouoein_john_8_12",
    "lemma": "ⲟⲩⲟⲉⲓⲛ",
    "matched_form": "ⲡⲟⲩⲟⲉⲓⲛ",
    "source_name": "Gospel of John (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲓⲱϩⲁⲛⲛⲏⲥ)",
    "reference": "John 8:12",
    "urn": "urn:cts:copticLit:nt.john.sahidica:8.12",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲁⲛⲟⲕ ⲡⲉ ⲡⲟⲩⲟⲉⲓⲛ ⲙⲡⲕⲟⲥⲙⲟⲥ ⲡⲉⲧⲟⲩⲏϩ ⲛⲥⲱⲓ ⲛⲛⲉϥⲙⲟⲟϣⲉ ϩⲙ ⲡⲕⲁⲕⲉ ⲁⲗⲗⲁ ϥⲛⲁϫⲓ ⲙⲡⲟⲩⲟⲉⲓⲛ ⲙⲡⲱⲛϩ.",
    "english_translation": "I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.",
    "arabic_translation": "أَنَا هُوَ نُورُ الْعَالَمِ. مَنْ يَتْبَعْنِي فَلاَ يَمْشِي فِي الظُّلْمَةِ بَلْ يَكُونُ لَهُ نُورُ الْحَيَاةِ."
  },
  {
    "id": "cit_hirini_john_14_27",
    "lemma": "ϩⲓⲣⲏⲛⲏ",
    "matched_form": "ϯϩⲓⲣⲏⲛⲏ",
    "source_name": "Gospel of John (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲓⲱϩⲁⲛⲛⲏⲥ)",
    "reference": "John 14:27",
    "urn": "urn:cts:copticLit:nt.john.sahidica:14.27",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ϯⲕⲱ ⲛⲏⲧⲛ ⲛϯϩⲓⲣⲏⲛⲏ ⲧⲁϩⲓⲣⲏⲛⲏ ϯϯ ⲙⲙⲟⲥ ⲛⲏⲧⲛ ⲛⲕⲁⲧⲁ ⲧϩⲉ ⲁⲛ ⲉⲧⲉⲣⲉ ⲡⲕⲟⲥⲙⲟⲥ ϯ ϯϯ ⲙⲙⲟⲥ ⲁⲛⲟⲕ ⲛⲏⲧⲛ.",
    "english_translation": "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.",
    "arabic_translation": "سَلاَماً أَتْرُكُ لَكُمْ. سَلاَمِي أُعْطِيكُمْ. لَيْسَ كَمَا يُعْطِي الْعَالَمُ أُعْطِيكُمْ أَنَا."
  },
  {
    "id": "cit_ekklhsia_matt_16_18",
    "lemma": "ⲉⲕⲕⲗⲏⲥⲓⲁ",
    "matched_form": "ⲧⲁⲉⲕⲕⲗⲏⲥⲓⲁ",
    "source_name": "Gospel of Matthew (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲙⲁⲑⲑⲁⲓⲟⲥ)",
    "reference": "Matthew 16:18",
    "urn": "urn:cts:copticLit:nt.matt.sahidica:16.18",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲉϫⲛ ⲧⲉⲓⲡⲉⲧⲣⲁ ϯⲛⲁⲕⲱⲧ ⲛⲧⲁⲉⲕⲕⲗⲏⲥⲓⲁ ⲁⲩⲱ ⲙⲡⲩⲗⲏ ⲛⲁⲙⲛⲧⲉ ⲛⲛⲉⲩϭⲙϭⲟⲙ ⲉⲣⲟⲥ.",
    "english_translation": "Upon this rock I will build my church; and the gates of hell shall not prevail against it.",
    "arabic_translation": "عَلَى هذِهِ الصَّخْرَةِ أَبْني كَنِيسَتِي، وَأَبْوَابُ الْجَحِيمِ لَنْ تَقْوَى عَلَيْهَا."
  },
  {
    "id": "cit_diakonos_1tim_3_8",
    "lemma": "ⲇⲓⲁⲕⲟⲛⲟⲥ",
    "matched_form": "ⲛⲇⲓⲁⲕⲟⲛⲟⲥ",
    "source_name": "First Epistle to Timothy (ⲧⲉⲡⲓⲥⲧⲟⲗⲏ ⲡⲣⲟⲥ ⲧⲓⲙⲟⲑⲉⲟⲥ ⲁ)",
    "reference": "1 Timothy 3:8",
    "urn": "urn:cts:copticLit:nt.1tim.sahidica:3.8",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲛⲇⲓⲁⲕⲟⲛⲟⲥ ϩⲱⲟⲩ ⲟⲛ ⲛⲧⲉⲓϩⲉ ⲉⲩⲥⲉⲙⲛⲟⲥ ⲛϩⲏⲧ ⲉⲛϩⲉⲛⲇⲓⲗⲟⲅⲟⲥ ⲁⲛ ⲛⲉ.",
    "english_translation": "Likewise must the deacons be grave, not doubletongued, not given to much wine, not greedy of filthy lucre.",
    "arabic_translation": "كَذلِكَ يَجِبُ أَنْ يَكُونَ الشَّمَامِسَةُ ذَوِي وَقَارٍ، لاَ ذَوِي لِسَانَيْنِ."
  },
  {
    "id": "cit_rome_gen_1_26",
    "lemma": "ⲣⲱⲙⲉ",
    "matched_form": "ⲟⲩⲣⲱⲙⲉ",
    "source_name": "Genesis (ⲅⲉⲛⲉⲥⲓⲥ - CoptOT)",
    "reference": "Genesis 1:26",
    "urn": "urn:cts:copticLit:ot.gen.coptot:1.26",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲁⲩⲱ ⲡⲉϫⲉ ⲡⲛⲟⲩⲧⲉ ϫⲉ ⲙⲁⲣⲛⲧⲁⲙⲓⲟ ⲛⲟⲩⲣⲱⲙⲉ ⲕⲁⲧⲁ ⲧⲉⲛϩⲓⲕⲱⲛ ⲙⲛ ⲡⲉⲛⲉⲓⲛⲉ.",
    "english_translation": "And God said, Let us make man in our image, after our likeness.",
    "arabic_translation": "وَقَالَ اللهُ: 'نَعْمَلُ الإِنْسَانَ عَلَى صُورَتِنَا كَشَبَهِنَا.'"
  },
  {
    "id": "cit_smou_ps_103_1",
    "lemma": "ⲥⲙⲟⲩ",
    "matched_form": "ⲥⲙⲟⲩ",
    "source_name": "Psalms of David (ⲯⲁⲗⲧⲏⲣⲓⲟⲛ - CoptOT)",
    "reference": "Psalm 103:1 (LXX 102:1)",
    "urn": "urn:cts:copticLit:ot.pss.coptot:102.1",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲥⲙⲟⲩ ⲧⲁⲯⲩⲭⲏ ⲉⲡϫⲟⲉⲓⲥ ⲁⲩⲱ ⲛⲉⲧϩⲛ ⲧⲁϩⲟⲩⲛ ⲧⲏⲣⲟⲩ ⲉⲡⲉϥⲣⲁⲛ ⲉⲧⲟⲩⲁⲁⲃ.",
    "english_translation": "Bless the Lord, O my soul: and all that is within me, bless his holy name.",
    "arabic_translation": "بَارِكِي يَا نَفْسِي الرَّبَّ، وَكُلُّ مَا فِي بَاطِنِي لِيُبَارِكِ اسْمَهُ الْقُدُّوسَ."
  },
  {
    "id": "cit_mntouro_matt_6_10",
    "lemma": "ⲙⲛⲧⲟⲩⲣⲟ",
    "matched_form": "ⲧⲉⲕⲙⲛⲧⲟⲩⲣⲟ",
    "source_name": "Gospel of Matthew (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲙⲁⲑⲑⲁⲓⲟⲥ)",
    "reference": "Matthew 6:10",
    "urn": "urn:cts:copticLit:nt.matt.sahidica:6.10",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲙⲁⲣⲉⲥⲉⲓ ⲛϭⲓ ⲧⲉⲕⲙⲛⲧⲟⲩⲣⲟ ⲙⲁⲣⲉ ⲡⲉⲕⲟⲩⲱϣ ϣⲱⲡⲉ ⲛⲧϩⲉ ⲉⲧϥϩⲛ ⲧⲡⲉ ϩⲓϫⲙ ⲡⲕⲁϩ.",
    "english_translation": "Thy kingdom come, Thy will be done in earth, as it is in heaven.",
    "arabic_translation": "لِيَأْتِ مَلَكُوتُكَ. لِتَكُنْ مَشِيئَتُكَ كَمَا فِي السَّمَاءِ كَذلِكَ عَلَى الأَرْضِ."
  },
  {
    "id": "cit_kyrios_rom_10_9",
    "lemma": "ⲕⲩⲣⲓⲟⲥ",
    "matched_form": "ⲡϫⲟⲉⲓⲥ",
    "source_name": "Epistle to the Romans (ⲧⲉⲡⲓⲥⲧⲟⲗⲏ ⲡⲣⲟⲥ ⲣⲱⲙⲁⲓⲟⲩⲥ)",
    "reference": "Romans 10:9",
    "urn": "urn:cts:copticLit:nt.rom.sahidica:10.9",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ϫⲉ ⲉⲕϣⲁⲛϩⲟⲙⲟⲗⲟⲅⲉⲓ ϩⲛ ⲣⲱⲕ ϫⲉ ⲡϫⲟⲉⲓⲥ ⲡⲉ ⲓⲏⲥⲟⲩⲥ ⲁⲩⲱ ⲛⲅⲡⲓⲥⲧⲉⲩⲉ ϩⲙ ⲡⲉⲕϩⲏⲧ ϫⲉ ⲁ ⲡⲛⲟⲩⲧⲉ ⲧⲟⲩⲛⲟⲥϥ ⲉⲃⲟⲗ ϩⲛ ⲛⲉⲧⲙⲟⲟⲩⲧ ⲕⲛⲁⲟⲩϫⲁⲓ.",
    "english_translation": "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.",
    "arabic_translation": "لأَنَّكَ إِنِ اعْتَرَفْتَ بِفَمِكَ بِالرَّبِّ يَسُوعَ، وَآمَنْتَ بِقَلْبِكَ أَنَّ اللهَ أَقَامَهُ مِنَ الأَمْوَاتِ، خَلَصْتَ."
  },
  {
    "id": "cit_aggelos_luke_2_10",
    "lemma": "ⲁⲅⲅⲉⲗⲟⲥ",
    "matched_form": "ⲡⲁⲅⲅⲉⲗⲟⲥ",
    "source_name": "Gospel of Luke (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲗⲟⲩⲕⲁⲥ)",
    "reference": "Luke 2:10",
    "urn": "urn:cts:copticLit:nt.luke.sahidica:2.10",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲡⲉϫⲉ ⲡⲁⲅⲅⲉⲗⲟⲥ ⲛⲁⲩ ϫⲉ ⲙⲡⲣⲣϩⲟⲧⲉ ⲉⲓⲥ ϩⲏⲏⲧⲉ ⲅⲁⲣ ϯⲧⲁϣⲉⲟⲉⲓϣ ⲛⲏⲧⲛ ⲛⲟⲩⲛⲟϭ ⲛⲣⲁϣⲉ.",
    "english_translation": "And the angel said unto them, Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people.",
    "arabic_translation": "فَقَالَ لَهُمُ الْمَلاَكُ: 'لاَ تَخَافُوا! فَهَا أَنَا أُبَشِّرُكُمْ بِفَرَحٍ عَظِيمٍ يَكُونُ لِجَمِيعِ الشَّعْبِ.'"
  },
  {
    "id": "cit_sotm_mark_4_9",
    "lemma": "ⲥⲱⲧⲙ",
    "matched_form": "ⲥⲱⲧⲙ",
    "source_name": "Gospel of Mark (ⲡⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲕⲁⲧⲁ ⲙⲁⲣⲕⲟⲥ)",
    "reference": "Mark 4:9",
    "urn": "urn:cts:copticLit:nt.mark.sahidica:4.9",
    "genre": "biblical",
    "dialect": "Sahidic",
    "coptic_text": "ⲡⲉⲧⲉ ⲟⲩⲛⲧϥ ⲙⲁⲁϫⲉ ⲙⲙⲁⲩ ⲉⲥⲱⲧⲙ ⲙⲁⲣⲉϥⲥⲱⲧⲙ.",
    "english_translation": "And he said unto them, He that hath ears to hear, let him hear.",
    "arabic_translation": "مَنْ لَهُ أُذُنَانِ لِلسَّمْعِ فَلْيَسْمَعْ."
  },
  {
    "id": "cit_besa_monastic_virtue",
    "lemma": "ⲙⲟⲛⲁⲭⲟⲥ",
    "matched_form": "ⲡⲙⲟⲛⲁⲭⲟⲥ",
    "source_name": "Besa: Letters and Exhortations (MONB.BA)",
    "reference": "Besa, Exhortations 2:9",
    "urn": "urn:cts:copticLit:besa.exhortations.monbba:2.9",
    "genre": "monastic",
    "dialect": "Sahidic",
    "coptic_text": "ⲡⲙⲟⲛⲁⲭⲟⲥ ⲉⲧⲙⲉ ⲙⲡϫⲟⲉⲓⲥ ϣⲁϥϩⲁⲣⲉϩ ⲉⲛⲉⲛⲧⲟⲗⲏ ⲧⲏⲣⲟⲩ ⲙⲡⲉⲛⲉⲓⲱⲧ ϣⲉⲛⲟⲩⲧⲉ.",
    "english_translation": "The monk who loves the Lord keeps all the commandments of our father Shenoute.",
    "arabic_translation": "الراهب الذي يحب الرب يحفظ جميع وصايا أبينا شنودة."
  }
]

out_path = 'd:/Copto/dictionary/data/corpus_concordance.json'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(concordance_entries, f, ensure_ascii=False, indent=2)

print(f"SUCCESS: Saved {len(concordance_entries)} verified manuscript citations to {out_path}")
